### ISSUE TITLE
Does this extension still work for the latest chrome?

### ISSUE THREAD

**Issue by ilazarte** [kdzwinel/CSS-Diff#15]
I don't see the tab in the right panel despite having element selected and CSS diff extension enabled.

**Comment by kdzwinel** [comment]
Can you please provide cssdiff version, browser version and a screenshot?
Also, was it there before and dissapeared or are you a new user? If you are
a new user, make sure to see cssdiff video in the chrome web store. Thanks.

**Comment by ilazarte** [comment]
Nvm, looks like it works as expected.  Same thing I was doing earlier suddenly started working.  Sorry about that.

**Comment by kdzwinel** [comment]
Np. You have to restart devtools after install. It was probably that.
