### ISSUE TITLE
No CSS Diff in Chrome 52.0.2743.116

### ISSUE THREAD

**Issue by Michael-F-Ellis** [kdzwinel/CSS-Diff#16]
Installed just now from the Chrome store.  Can't find the CSS Diff tab in anywhere in DevTools when I inspect an element.  Extension manager shows CSS Diff enabled.

**Comment by Michael-F-Ellis** [comment]
Never mind! Need to use the >> button to expose it.  Sorry for the noise.

**Comment by kdzwinel** [comment]
No worries. Enjoy!
