### ISSUE TITLE
Option to change colors for the dark themed devtools

### ISSUE THREAD

**Issue by modulexcite** [kdzwinel/CSS-Diff#17]
Thank you for an excellent extension.
I've zero dark matrix devtools theme installed and the colors for this extension do not play well with that or vice-versa. It would be nice to have an option to change the color scheme.

**Comment by kdzwinel** [comment]
Thanks for using CSS-Diff and reporting that! This should be a css-only change. From what I know dark version of devtools adds some top-level class that can be used to influence styles of the extension. Feel free to take a stab on this, I'll be happy to help.

**Comment by rodfersou** [comment]
Awesome extension!

Also I'm getting some issues with the default dark theme of google chrome. Could you please take a look?

**Comment by DoMiNeLa10** [comment]
I can confirm that this extension is borderline unreadable with the default dark theme.

**Comment by kdzwinel** [comment]
Again, please feel free to take a stab at this, it's a "help wanted" task. I'll be happy to review and deploy it.

**Comment by rodfersou** [comment]
@kdzwinel unfortunately I don't have experience developing extensions, can you please add the basic steps on the readme of the package describing how to do it?

**Comment by rodfersou** [comment]
or maybe point out where I can find this information

**Comment by DoMiNeLa10** [comment]
I wrote styles that work properly with the dark theme and made a pr for them: https://github.com/kdzwinel/CSS-Diff/pull/21
It should be pulled after another PR which upgrades dependencies of the build system which was broken.

**Comment by kdzwinel** [comment]
Thanks a ton @DoMiNeLa10 ! I'll review, and hopefully merge it, over the weekend.

**Comment by kdzwinel** [comment]
Thanks to @DoMiNeLa10 we now have a dark mode!!! I'll publish it today in the web store.

<img width="761" alt="Screen Shot 2019-06-10 at 12 13 06" src="https://user-images.githubusercontent.com/985504/59189161-b37b0b80-8b79-11e9-806b-7e2fcd970885.png">
