### ISSUE TITLE
broken in Chrome 66?

### ISSUE THREAD

**Issue by jbeyer05** [kdzwinel/CSS-Diff#19]
First off, I'm a huge fan of CSS Diff.
Since upgrading to Chrome 66, I don't see the CSS Diff tab in developer tools, although it is still installed.  Perhaps Chrome 66 update broke something?

**Comment by jbeyer05** [comment]
Thanks for the speedy response.  Removing the extension and re-installing it has fixed it.  Should have tried that before I bothered you.

**Comment by kdzwinel** [comment]
No worries, I'm happy to hear it works 👍
