### ISSUE TITLE
No LICENSE file

### ISSUE THREAD

**Issue by DoMiNeLa10** [kdzwinel/CSS-Diff#22]
This repository doesn't have a LICENSE file, which normally means the owner has exclusive copyright, but GitHub's ToS overrides that. You might want to add a license to this repository to make it clear how this extension can be used and who owns the rights to it.

https://choosealicense.com/no-permission/

**Comment by kdzwinel** [comment]
Good call, license was only mentioned in the package.json. I added a https://github.com/kdzwinel/CSS-Diff/blob/master/LICENSE file.
