### ISSUE TITLE
Extension is missing in Chrome store

### ISSUE THREAD

**Issue by zerocity** [kdzwinel/CSS-Diff#26]
Hi , 

the link (https://chrome.google.com/webstore/detail/css-diff/pefnhibkhcfooofgmgoipfpcojnhhljm) to the chrome extension is dead.

**Comment by kdzwinel** [comment]
Right, sorry for the confusion, I pulled all of my extensions from web store (some context: https://twitter.com/kdzwinel/status/1213070289292210176 ). Please install from github directly (I updated the readme file). Thank you!

**Comment by ryantheleach** [comment]
I understand your decision, but I was mildly annoyed / thought I was going nuts when I could no longer find it. Is there a way to direct this annoyance to help you extension guys out a little / direct it at google?

(Also, thanks a ton, I find this really useful in niche cases)
