### ISSUE TITLE
Can't copy text

### ISSUE THREAD

**Issue by WileESpaghetti** [kdzwinel/CSS-Diff#9]
I would like to be able to copy the text on the right column of the diffs.

Example:
If each thing I am comparing uses a slightly different text color, I would like to be able to select the text color of one of them so I can make them both match.

**Comment by kdzwinel** [comment]
Sorry it took ages to respond and thank you for these bug reports.

Interestingly, it's Chrome that blocks selecting by default. No idea why, but since it's only CSS I was able to fix that with `-webkit-user-select: initial;`. This will be shipped in version 0.4 .
